name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Add email sending action here
    - name: Send Email
      uses: hilarion5/send-mail@v1
      with:
        smtp-server: smtp.gmail.com
        smtp-port: 465
        smtp-secure: true
        from-email: automationmail92@gmail.com
        to-email: dummytestt15@gmail.com
        username: automationmail92@gmail.com
        password: cujcugsjdxgdkqxf
        subject: Test Email
        body: This is a test email sent from GitHub Actions.
        html: |
          <h1>This is a test email</h1>
          <p>Test Paragraph</p>
