name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -Dtest=SendAppInvitationToPatient#shouldVerifyThatTheAdminSendApp
    
    # Add a step to list the contents of the directory for debugging
    - name: List Directory Contents
      if: always()
      run: ls -l target/surefire-reports

    # Print out the contents of the testformail.html file for debugging
    - name: Print testformail.html
      if: always()
      run: cat target/surefire-reports/testformail.html
    
    # Add email sending action with if condition
    - name: Send Email docdok
      if: always()
      uses: hilarion5/send-mail@v1
      with:
        smtp-server: smtp.gmail.com
        smtp-port: 465
        smtp-secure: true
        from-email: automationmail92@gmail.com
        to-email: dummytestt15@gmail.com
        username: automationmail92@gmail.com
        password: cujcugsjdxgdkqxf
        subject: DocDok Github Actions
        body: Test msg
        html: |
          <h1>This is a test email</h1>
          <p>Test Paragraph</p>
