name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    # Add a step to list the contents of the directory for debugging
    - name: List Directory Contents
      if: always()
      run: ls -l target/surefire-reports

    # Print out the contents of the emailable-report.html file for debugging
    - name: Print emailable-report.html
      if: always()
      run: cat target/surefire-reports/emailable-report.html
    
    # Add email sending action with if condition
    - name: Send Email with Attachment
      if: always()
      uses: hilarion5/send-mail@v1
      with:
        smtp-server: smtp.gmail.com
        smtp-port: 465
        smtp-secure: true
        from-email: automationmail92@gmail.com
        to-email: dummytestt15@gmail.com
        username: automationmail92@gmail.com
        password: cujcugsjdxgdkqxf
        subject: DocDok Github Actions
        body: This is a test email sent from GitHub Actions.
        html_body: "<h1>This is a test email of docDok</h1><p>Greeting from DocDok</p>"
        attachments: |
          target/surefire-reports/testformail.html
