name: Connect to VPN

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  connect-vpn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Connect to VPN
        run: sudo openvpn --config .github/workflows/client.ovpn --daemon
